inherit_from: .rubocop_todo.yml

# Cop supports --auto-correct.
# Configuration parameters: TreatCommentsAsGroupSeparators, ConsiderPunctuation, Include.
# Include: **/*.gemfile, **/Gemfile, **/gems.rb
Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, IndentationWidth.
# SupportedStyles: with_first_argument, with_fixed_indentation
Layout/ArgumentAlignment:
  Exclude:
    - 'bin/webpack'
    - 'bin/webpack-dev-server'

# Cop supports --auto-correct.
Layout/EmptyLineAfterGuardClause:
  Exclude:
    - 'bin/bundle'

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: empty_lines, no_empty_lines
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, IndentationWidth.
# SupportedStyles: aligned, indented
Layout/MultilineOperationIndentation:
  Exclude:
    - 'bin/bundle'

# Configuration parameters: IgnoredMethods, CountRepeatedAttributes.
Metrics/AbcSize:
  Max: 18

# Configuration parameters: CountComments, CountAsOne, ExcludedMethods, IgnoredMethods.
# IgnoredMethods: refine
Metrics/BlockLength:
  Max: 50

# Configuration parameters: IgnoredMethods.
Metrics/CyclomaticComplexity:
  Max: 9

# Configuration parameters: CountComments, CountAsOne, ExcludedMethods, IgnoredMethods.
Metrics/MethodLength:
  Max: 18

# Configuration parameters: IgnoredMethods.
Metrics/PerceivedComplexity:
  Max: 9

# Configuration parameters: AllowedChars.
# AllowedChars: ©
Style/AsciiComments:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/sign_in_helper.rb'
    - 'test/test_helper.rb'

# Configuration parameters: AllowedConstants.
Style/Documentation:
  Enabled: false

# Cop supports --auto-correct.
Style/EmptyCaseCondition:
  Exclude:
    - 'test/sign_in_helper.rb'

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: compact, expanded
Style/EmptyMethod:
  Exclude:
    - 'app/controllers'

# Cop supports --auto-correct.
Style/ExpandPathArguments:
  Exclude:
    - 'bin/bundle'

# Cop supports --auto-correct.
Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'

# Cop supports --auto-correct.
Style/IfUnlessModifier:
  Exclude:
    - 'app/controllers/events_controller.rb'
    - 'app/controllers/tickets_controller.rb'
    - 'app/models/event.rb'
    - 'app/models/user.rb'

# Cop supports --auto-correct.
# Configuration parameters: MinDigits, Strict.
Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

# Cop supports --auto-correct.
Style/PerlBackrefs:
  Exclude:
    - 'bin/bundle'

# Cop supports --auto-correct.
Style/RedundantBegin:
  Exclude:
    - 'bin/yarn'

# Cop supports --auto-correct.
# Configuration parameters: SafeForConstants.
Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'

# Cop supports --auto-correct.
# Configuration parameters: .
# SupportedStyles: use_perl_names, use_english_names
Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

# Cop supports --auto-correct.
Style/StderrPuts:
  Exclude:
    - 'bin/yarn'

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, MinSize.
# SupportedStyles: percent, brackets
Style/SymbolArray:
  Exclude:
    - 'Gemfile'
    - 'db/migrate/20210220235152_create_active_storage_tables.active_storage.rb'

# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 198
